[all]
exclude-files = [
    "crates/foundation/src/exchange_rates.rs",
    "crates/render-typst/src/compare_images.rs",
    "crates/render-typst/src/render.rs",
    "crates/cli/src/init_logging.rs",
    "crates/cli/src/input/tui/**",
    "crates/cli/src/main.rs",
    "crates/cli/src/run.rs",
    "crates/cli/src/dispatch_command.rs",
    "crates/core-invoice/src/logic/send_email.rs",
]
verbose = false
timeout = "2m"
locked = true
all-features = true
jobs = 1
out = ["Html"]
